version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/share/applications/simplenode
permissions:
  - object: /usr/local/share/applications/simplenode
    owner: ec2-user
    group: ec2-user
