version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/share/applications/simplenode
permissions:
  - object: /usr/local/share/applications/simplenode
    owner: ec2-user
    group: ec2-user
hooks:
    -ApplicationStart: /usr/local/share/applications/simplenode/run_server.sh
    timeout: 20
    runas: ec2-user